Repository teamSeven71/TechTalk, pull requests merged in 2024-04, with the labels that each got.

#29 Feat: "login signup 페이지 연결, 권한별 접근 페이지 제한 시작"
  src/main/java/community/config/JwtSecurityConfiguration.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/mapper/user/UserMapper.java
  src/main/resources/static/css/join.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/main/resources/templates/site/Join.html
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/forms/header.html
  src/main/resources/templates/site/login.html
  src/main/resources/templates/site/main.html
  src/main/resources/templates/site/writeArticle.html
Labels: confirm

#30 Feat : "comment thyme leaf 구문 적용"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/CommentController.java
  src/main/java/community/repository/CommentRepository.java
  src/main/java/community/service/CommentService.java
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/articleDetail.html
Labels: enhancement

#37 Feat : "댓글 관련 기능 연동 완료"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/repository/CommentRepository.java
  src/main/java/community/service/CommentService.java
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/articleDetail.html
Labels: enhancement

#38 Refactor : "게시물 리스트 페이지 조회 & 게시글 생성 기능 완료"
  src/main/java/community/controller/ArticleController.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/dto/user/ArticleDto.java
  src/main/java/community/repository/ArticleCategoryRepository.java
  src/main/java/community/repository/CategoryRepository.java
  src/main/java/community/service/ArticleCategoryService.java
  src/main/java/community/service/ArticleService.java
  src/main/java/community/service/CategoryService.java
  src/main/resources/data.sql
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/writeArticle.html
Labels: enhancement

#41 Feature: "initclass 생성"
  src/main/java/community/Init.java
  src/main/resources/data.sql
Labels: confirm

#43 Feat : "보현님 bracnch merge및 사이드 코드 수정"
  src/main/java/community/config/SecurityConfiguration.java
  src/main/java/community/controller/ArticleController.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/dto/user/ArticleDto.java
  src/main/java/community/mapper/user/ArticleMapper.java
  src/main/java/community/repository/ArticleCategoryRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/templates/site/Join.html
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/login.html
  src/main/resources/templates/site/main.html
  src/main/resources/templates/site/writeArticle.html
Labels: enhancement

#44 Refactor : "article Details 관련 api 구현"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/repository/ArticleCategoryRepository.java
  src/main/java/community/repository/CommentRepository.java
  src/main/java/community/service/ArticleCategoryService.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/articleDetail.html
Labels: enhancement

#48 Feature: "userPage UI 구현"
  src/main/resources/static/css/userPage.css
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/userPage.html
Labels: confirm

#49 Design : "게시글 상세 UI 수정 및 카테고리 url 경로 설정"
  src/main/resources/templates/site/articleDetail.html
Labels: confirm

#50 Feature/update UI
  src/main/java/community/controller/UserViewController.java
  src/main/resources/static/css/adminPage.css
  src/main/resources/static/css/articleCreate.css
  src/main/resources/static/css/articleList.css
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/writeArticle.html
Labels: confirm

#51 Feature/join page
  src/main/java/community/config/SecurityConfiguration.java
  src/main/java/community/controller/UserController.java
  src/main/java/community/dto/user/CheckDuplicateRequest.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/js/join.js
  src/main/resources/templates/site/Join.html
Labels: enhancement

#52 Feature/update UI
  src/main/resources/static/css/custom.css
  src/main/resources/static/img/blog/comments-1.jpg
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
Labels: confirm

#54 Feature: "categoryName 타임리프 추가"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/dto/user/ArticleDto.java
  src/main/java/community/mapper/user/ArticleMapper.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/main.html
Labels: confirm

#55 Fix: "삭제 기능 작동오류 해결"
  src/main/java/community/Init.java
  src/main/java/community/controller/UserController.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/site/adminPage.html
Labels: bug

#56 Feature/category name
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/static/css/adminPage.css
  src/main/resources/static/css/articleCreate.css
  src/main/resources/static/css/articleList.css
  src/main/resources/static/css/custom.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/userPage.css
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/main.html
  src/main/resources/templates/site/writeArticle.html
Labels: confirm

#57 Feature/user page
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/js/userInfo.js
  src/main/resources/templates/site/main.html
  src/main/resources/templates/site/userPage.html
Labels: enhancement

#58 Feat : "Pagination 기능 구현"
  src/main/java/community/Init.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/dto/user/UserDto.java
  src/main/java/community/repository/ArticleCategoryRepository.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleList.html
Labels: enhancement

#60 Fix : "버그 수정"
  src/main/java/community/Init.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/writeArticle.html
Labels: bug, confirm

#61 Fix: "id -> email 수정"
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/service/UserService.java
  src/main/resources/templates/site/writeArticle.html
Labels: confirm

#64 Fix : "자기 자신이 작성한 댓글 지워도 db에 안지워지는 오류 수정"
  src/main/java/community/service/CommentService.java
Labels: bug, confirm

#65 Feat: "내용이 비어있으면 내용을 입력하게 유도"
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/writeArticle.html
Labels: enhancement

#69 Feat : "검색 기능 구현"
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/articleList.js
Labels: confirm

#72 Feature/view count
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/mapper/user/ArticleMapper.java
  src/main/java/community/repository/ArticleRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/static/img/img_down/comment.png
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
Labels: confirm

#73 Fix : "검색 기능 수정 완료"
  src/main/java/community/Init.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/repository/ArticleCategoryRepository.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/articleList.js
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleList.html
Labels: bug, enhancement

#74 Feature/view
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/service/ArticleService.java
Labels: confirm

#75 Feat : "database mysql로 변경"
  build.gradle
  src/main/java/community/Init.java
  src/main/java/community/config/SecurityConfiguration.java
  src/main/resources/data.sql
Labels: enhancement

#76 Feature "viewCount 수정 삭제"
  src/main/java/community/service/ArticleService.java
Labels: confirm

#77 Fix "viewCount 수정/ 태그 기호 수정"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/domain/user/ArticleEntity.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/templates/site/articleDetail.html
Labels: confirm

#78 Feat : "간단한 기능 오류 및 디자인 수정"
  src/main/java/community/controller/UserController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/service/ArticleCategoryService.java
  src/main/java/community/service/ArticleService.java
  src/main/java/community/service/CommentService.java
  src/main/resources/static/css/articleList.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/userPage.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/main.html
Labels: bug, confirm

#80 Feat: "유저정보 페이지 개선, 글 상세 페이지 개선"
  build.gradle
  src/main/java/community/Init.java
  src/main/java/community/config/SecurityConfiguration.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/exception/DuplicateEmailException.java
  src/main/java/community/exception/DuplicateNicknameException.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/static/css/userPage.css
  src/main/resources/static/js/userInfo.js
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/userPage.html
Labels: enhancement

#82 Fix : "메인 페이지 공지사항 버튼 오류 수정"
  src/main/resources/templates/site/main.html
Labels: bug, confirm

#83 Feat: "유저 정보 확인 오류"
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/js/main.js
  src/test/java/community/controller/ArticleControllerTest.java
  src/test/java/community/controller/ArticlePageControllerTest.java
Labels: bug

#88 Fix: "유저 정보 변경 후 글 생성 버그"
  src/main/java/community/controller/UserViewController.java
Labels: bug

#89 Fix: 테스트코드 삭제
  src/test/java/community/controller/ArticleControllerTest.java
  src/test/java/community/controller/ArticlePageControllerTest.java
Labels: bug
