Repository teamSeven71/TechTalk, pull requests merged in 2024-03, with the labels that each got.

#1 Feat: "게시물 조회 api 구현"
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/community/controller/ArticleController.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/repository/ArticleRepository.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/java/community/service/UserService.java
  src/main/resources/data.sql
Labels: enhancement

#9 Design:"메인페이지 UI 구현"
  src/main/resources/templates/site/index.html
Labels: confirm

#10 Design: "게시글 작성 페이지 UI구현"
  src/main/resources/templates/site/assets/css/articleCreate.css
  src/main/resources/templates/site/assets/js/article.js
  src/main/resources/templates/site/writeArticle.html
Labels: enhancement

#11 Feat: "인메모리 로그인 구현, JwtSecurityConfiguration추가"
  build.gradle
  src/main/java/community/config/JwtSecurityConfiguration.java
  src/main/java/community/domain/user/UserEntity.java
  src/main/java/community/dto/user/UserDto.java
Labels: enhancement

#12 Fix: "data.sql 수정"
  src/main/resources/data.sql
Labels: bug

#14 Feat : "CRUD api 구현 및 resources 파일 수정"
  src/main/java/community/Community.java
  src/main/java/community/config/SwaggerConfig.java
  src/main/java/community/controller/ArticleController.java
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/domain/user/ArticleEntity.java
  src/main/java/community/domain/user/UserEntity.java
  src/main/java/community/dto/user/ArticleDto.java
  src/main/java/community/exception/ArticleNotFoundException.java
  src/main/java/community/exception/UnauthorizedException.java
  src/main/java/community/mapper/user/ArticleMapper.java
  src/main/java/community/mapper/user/UserMapper.java
  src/main/java/community/repository/ArticleRepository.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/static/css/articleCreate.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/article.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/free.html
  src/main/resources/templates/site/index.html
  src/main/resources/templates/site/writeArticle.html
Labels: enhancement

#13 Feature/login UI
  src/main/resources/templates/site/assets/css/login.css
  src/main/resources/templates/site/login.html
Labels: confirm

#15 Feat: "회원가입/로그인 프로토타입 + SpringSecurity설정"
  src/main/java/community/config/JwtSecurityConfiguration.java
  src/main/java/community/controller/UserController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/domain/user/UserEntity.java
  src/main/java/community/dto/user/AddUserRequest.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/UserService.java
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement

#16 Feat : 수정, 삭제 api 수정 및 확인
  src/main/java/community/controller/ArticleController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/domain/user/UserEntity.java
  src/main/java/community/dto/user/ArticleDto.java
  src/main/java/community/service/ArticleService.java
  src/main/resources/static/js/article.js
  src/main/resources/templates/site/articleDetail.html
Labels: enhancement

#17 Feat: "JWTDecoder 설정"
  src/main/java/community/config/JwtSecurityConfiguration.java
Labels: confirm

#19 Design : "Feature/admin page UI"
  src/main/java/community/controller/ArticlePageController.java
  src/main/java/community/controller/UserViewController.java
  src/main/java/community/repository/UserRepository.java
  src/main/java/community/service/UserService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/index.html
Labels: enhancement

#20 Header footer UI
  src/main/resources/static/css/custom.css
  src/main/resources/templates/site/JavaScript.html
  src/main/resources/templates/site/Python.html
  src/main/resources/templates/site/SQL.html
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/etc.html
  src/main/resources/templates/site/forms/header.html
  src/main/resources/templates/site/free.html
  src/main/resources/templates/site/java.html
Labels: confirm

#24 Refactor : "파일 정리&UI 수정&코드 수정"
  src/main/resources/static/css/articleList.css
  src/main/resources/static/js/articleList.js
  src/main/resources/templates/site/adminPage.html
  src/main/resources/templates/site/articleDetail.html
  src/main/resources/templates/site/articleList.html
  src/main/resources/templates/site/forms/bootstrapForm.html
  src/main/resources/templates/site/forms/footer.html
  src/main/resources/templates/site/forms/header.html
  src/main/resources/templates/site/main.html
  src/main/resources/templates/site/writeArticle.html
Labels: confirm
